# Generated by Django 5.2.15 on 2026-06-28 07:13

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="activity_photos",
                    ),
                ),
                ("activity_date", models.DateField()),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-activity_date"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                (
                    "is_pinned",
                    models.BooleanField(default=False, help_text="Pin to top of list"),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SIO_LITERATURE", "SIO Literature"),
                            ("CONTEMPORARY", "Contemporary Literature"),
                        ],
                        default="SIO_LITERATURE",
                        max_length=50,
                    ),
                ),
                (
                    "cover_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="book_covers",
                    ),
                ),
                (
                    "drive_link",
                    models.URLField(help_text="Google Drive link to the PDF"),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("office_address", models.TextField()),
                (
                    "google_maps_embed_url",
                    models.URLField(blank=True, help_text="Google Maps embed URL"),
                ),
                (
                    "phone_numbers",
                    models.JSONField(default=list, help_text="List of phone numbers"),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "social_media_links",
                    models.JSONField(
                        default=dict,
                        help_text="Dict of social media links: {'facebook': 'url', 'instagram': 'url', ...}",
                    ),
                ),
                (
                    "google_form_link",
                    models.URLField(
                        blank=True, help_text="Google Form link for Join SIO"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("event_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=300)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("UPCOMING", "Upcoming"), ("PAST", "Past")],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero_banner_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="hero_banner",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_subtitle", models.CharField(blank=True, max_length=500)),
                (
                    "introduction",
                    models.TextField(
                        blank=True, help_text="Introduction to SIO RT Nagar"
                    ),
                ),
                ("vision", models.TextField(blank=True)),
                ("mission", models.TextField(blank=True)),
                (
                    "cta_join_text",
                    models.CharField(blank=True, default="Join Us", max_length=100),
                ),
                (
                    "cta_events_text",
                    models.CharField(
                        blank=True, default="Upcoming Events", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Page",
            },
        ),
        migrations.CreateModel(
            name="OfficeBearer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="office_bearer_photos",
                    ),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of display"
                    ),
                ),
            ],
            options={
                "verbose_name": "Office Bearer",
                "verbose_name_plural": "Office Bearers",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="event_photos"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=300)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Photo",
                "verbose_name_plural": "Event Photos",
            },
        ),
    ]
