# Generated by Django 5.2.15 on 2026-06-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.AddField(
            model_name="announcement",
            name="pinned_at",
            field=models.DateTimeField(
                blank=True, help_text="When the announcement was pinned", null=True
            ),
        ),
    ]
